DisplayDocter.java
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.io.*;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
public class DisplayDocter extends javax.swing.JFrame {
/**
* Creates new form DisplayDocter
*/
public DisplayDocter() {
initComponents();
}
/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {
jPanel1 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
jLabel3 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
namevar = new javax.swing.JLabel();
agevar = new javax.swing.JLabel();
phonenovar = new javax.swing.JLabel();
gendervar = new javax.swing.JLabel();
doctorvar = new javax.swing.JLabel();
problemvar = new javax.swing.JLabel();
jLabel13 = new javax.swing.JLabel();
timevar = new javax.swing.JLabel();
jPanel2 = new javax.swing.JPanel();
jLabel16 = new javax.swing.JLabel();
jLabel17 = new javax.swing.JLabel();
jButton1 = new javax.swing.JButton();
jLabel18 = new javax.swing.JLabel();
jLabel15 = new javax.swing.JLabel();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
jPanel1.setBackground(new java.awt.Color(51, 0, 153));
jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new
java.awt.Color(0, 0, 0)));
jLabel1.setForeground(new java.awt.Color(242, 242, 242));
jLabel1.setText("Name:");
jLabel2.setForeground(new java.awt.Color(242, 242, 242));
jLabel2.setText("Age:");
jLabel3.setForeground(new java.awt.Color(242, 242, 242));
jLabel3.setText("Phoneno.:");
jLabel4.setForeground(new java.awt.Color(242, 242, 242));
jLabel4.setText("Gender:");
jLabel5.setForeground(new java.awt.Color(242, 242, 242));
jLabel5.setText("Docter Name:");
jLabel6.setForeground(new java.awt.Color(242, 242, 242));
jLabel6.setText("Problem:");
namevar.setForeground(new java.awt.Color(242, 242, 242));
namevar.setText("jLabel7");
agevar.setForeground(new java.awt.Color(242, 242, 242));
agevar.setText("jLabel8");
phonenovar.setForeground(new java.awt.Color(242, 242, 242));
phonenovar.setText("jLabel9");
gendervar.setForeground(new java.awt.Color(242, 242, 242));
gendervar.setText("jLabel10");
doctorvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
doctorvar.setForeground(new java.awt.Color(242, 242, 242));
doctorvar.setText("jLabel11");
problemvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
problemvar.setForeground(new java.awt.Color(242, 242, 242));
problemvar.setText("jLabel12");
jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel13.setForeground(new java.awt.Color(242, 242, 242));
jLabel13.setText("Appointment Date & Time:");
timevar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
timevar.setForeground(new java.awt.Color(255, 51, 51));
timevar.setText("jLabel14");
javax.swing.GroupLayout jPanel1Layout = new
javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(31, 31, 31)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
TRAILING, false)
.addComponent(jLabel3,
javax.swing.GroupLayout.Alignment.LEADING,
javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
.addComponent(jLabel1,
javax.swing.GroupLayout.Alignment.LEADING,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel2,
javax.swing.GroupLayout.Alignment.LEADING,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
TRAILING, false)
.addComponent(namevar,
javax.swing.GroupLayout.Alignment.LEADING,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(agevar,
javax.swing.GroupLayout.Alignment.LEADING,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(gendervar,
javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
.addComponent(phonenovar,
javax.swing.GroupLayout.PREFERRED_SIZE, 101,
javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(58, 58, 58)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING, false)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING, false)
.addComponent(jLabel5,
javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
.addComponent(jLabel6,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING, false)
.addComponent(doctorvar,
javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
.addComponent(problemvar,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
.addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(timevar, javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addContainerGap(25, Short.MAX_VALUE))
);
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(17, 17, 17)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
BASELINE)
.addComponent(jLabel1)
.addComponent(jLabel5)
.addComponent(namevar)
.addComponent(doctorvar,
javax.swing.GroupLayout.PREFERRED_SIZE, 26,
javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
BASELINE)
.addComponent(jLabel6)
.addComponent(problemvar,
javax.swing.GroupLayout.PREFERRED_SIZE, 24,
javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
BASELINE)
.addComponent(agevar)
.addComponent(jLabel2)))
.addGap(18, 18, 18)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addComponent(jLabel13,
javax.swing.GroupLayout.PREFERRED_SIZE, 28,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel3)
.addComponent(phonenovar))
.addGap(3, 3, 3)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
BASELINE)
.addComponent(gendervar)
.addComponent(jLabel4))
.addComponent(timevar, javax.swing.GroupLayout.PREFERRED_SIZE,
26, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(27, Short.MAX_VALUE))
);
jPanel2.setBackground(new java.awt.Color(51, 0, 153));
jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new
java.awt.Color(0, 0, 0)));
jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel16.setForeground(new java.awt.Color(242, 242, 242));
jLabel16.setText("Pharmacy Details");
jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
jLabel17.setForeground(new java.awt.Color(242, 242, 242));
jLabel17.setText("For pharmacy Click here:");
jButton1.setText("Clickhere");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});
jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
jLabel18.setForeground(new java.awt.Color(242, 242, 242));
jLabel18.setText("Note: Pharmacy details are only visible after doctor
appointment");
javax.swing.GroupLayout jPanel2Layout = new
javax.swing.GroupLayout(jPanel2);
jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addGap(171, 171, 171)
.addComponent(jLabel16))
.addGroup(jPanel2Layout.createSequentialGroup()
.addGap(39, 39, 39)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addComponent(jLabel18)
.addGroup(jPanel2Layout.createSequentialGroup()
.addComponent(jLabel17,
javax.swing.GroupLayout.PREFERRED_SIZE, 162,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(jButton1)))))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE))
);
jPanel2Layout.setVerticalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE,
31, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
BASELINE)
.addComponent(jLabel17,
javax.swing.GroupLayout.PREFERRED_SIZE, 30,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton1))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel18)
.addContainerGap(32, Short.MAX_VALUE))
);
jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
jLabel15.setText("APPOINTMENT DETAILS");
javax.swing.GroupLayout layout = new
javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADIN
G)
.addGroup(layout.createSequentialGroup()
.addGap(63, 63, 63)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADIN
G, false)
.addComponent(jPanel1,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jPanel2,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
.addGroup(layout.createSequentialGroup()
.addGap(190, 190, 190)
.addComponent(jLabel15)))
.addContainerGap(40, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(21, 21, 21)
.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE,
32, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE))
);
pack();
}// </editor-fold>
String pname;
String page;
String pgenger;
String pproblem;
String ppassword;
String pphoneno;
String pdoctor;
public DisplayDocter(String name,String age,String gender,String problem,String
phoneno,String Doctor)
{
initComponents();
this.pname=name;
this.page=age;
this.pgenger=gender;
this.pproblem=problem;
this.pphoneno=phoneno;
this.pdoctor=Doctor;
namevar.setText(pname);
agevar.setText(page);
gendervar.setText(pgenger);
problemvar.setText(pproblem);
phonenovar.setText(pphoneno);
doctorvar.setText(pdoctor);
Calendar calendar = Calendar.getInstance();
SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
calendar.add(Calendar.MINUTE, 10);
timevar.setText(df.format(calendar.getTime()));
//Socket s = null;
//ObjectOutputStream t;
// try{
// s = new Socket("localhost", 5000);
//t = new ObjectOutputStream(s.getOutputStream());
//}
//catch (UnknownHostException e1) {
// e1.printStackTrace();}
//catch (IOException e1) {
// e1.printStackTrace();
// }
// try{
//BufferedReader response = new BufferedReader(new
InputStreamReader(s.getInputStream()));
//}
//catch (IOException e1) {
// e1.printStackTrace();
// }
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
(optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look
and feel.
* For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(DisplayDocter.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(DisplayDocter.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(DisplayDocter.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(DisplayDocter.class.getName()).log(java.util.loggi
ng.Level.SEVERE, null, ex);
}
//</editor-fold>
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new DisplayDocter().setVisible(true);
}
});
}
// Variables declaration - do not modify
private javax.swing.JLabel agevar;
private javax.swing.JLabel doctorvar;
private javax.swing.JLabel gendervar;
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel13;
private javax.swing.JLabel jLabel15;
private javax.swing.JLabel jLabel16;
private javax.swing.JLabel jLabel17;
private javax.swing.JLabel jLabel18;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JPanel jPanel1;
private javax.swing.JPanel jPanel2;
private javax.swing.JLabel namevar;
private javax.swing.JLabel phonenovar;
private javax.swing.JLabel problemvar;
private javax.swing.JLabel timevar;
// End of variables declaration
}
—-------------------------------------------------------------------------------------------------------
Logindetails.java
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JButton;
import java.awt.*;
import java.net.*;
import java.io.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.Base64;
public class Logindetails extends javax.swing.JFrame {
public Logindetails() {
initComponents();
}
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {
jPanel1 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
jButton1 = new javax.swing.JButton();
Usernamevar = new javax.swing.JLabel();
Passwordvar = new javax.swing.JLabel();
jLabel3 = new javax.swing.JLabel();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setBackground(new java.awt.Color(255, 102, 0));
jPanel1.setBackground(new java.awt.Color(51, 0, 102));
jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel1.setForeground(new java.awt.Color(242, 242, 242));
jLabel1.setText("Username:");
jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel2.setForeground(new java.awt.Color(242, 242, 242));
jLabel2.setText("Password:");
jButton1.setBackground(new java.awt.Color(255, 102, 0));
jButton1.setText("OK");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});
Usernamevar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
Usernamevar.setForeground(new java.awt.Color(242, 242, 242));
Usernamevar.setText("-------");
Passwordvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
Passwordvar.setForeground(new java.awt.Color(242, 242, 242));
Passwordvar.setText("-------");
javax.swing.GroupLayout jPanel1Layout = new
javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(41, 41, 41)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING, false)
.addComponent(jLabel1,
javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
.addComponent(jLabel2,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGap(34, 34, 34)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING, false)
.addComponent(Usernamevar,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(Passwordvar,
javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(125, 125, 125)
.addComponent(jButton1)))
.addContainerGap(75, Short.MAX_VALUE))
);
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(30, 30, 30)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
BASELINE)
.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
29, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(Usernamevar,
javax.swing.GroupLayout.PREFERRED_SIZE, 29,
javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
LEADING, false)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
28, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(Passwordvar,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGap(3, 3, 3)))
.addGap(18, 18, 18)
.addComponent(jButton1)
.addContainerGap(44, Short.MAX_VALUE))
);
jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
jLabel3.setText("Your Login Details");
javax.swing.GroupLayout layout = new
javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(40, 40, 40)
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(48, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE)
.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
255, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(70, 70, 70))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44,
Short.MAX_VALUE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(34, 34, 34))
);
pack();
}// </editor-fold>
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
new
DisplayDocter(pname,page,pgender,pproblem,Uname,pdoctor).setVisible(true);
}
String Uname;
String Pword;
String page;
String pname;
String pgender;
String pproblem;
String pdoctor="error";
public Logindetails(String name,String age,String gender,String problem,String
Username, String Password,String doctor)
{ initComponents();
this.Uname=Username;
Usernamevar.setText(Uname);
this.Pword=Password;
Passwordvar.setText(Pword);
this.page=age;
this.pname=name;
this.pgender=gender;
this.pproblem=problem;
this.pdoctor=doctor;
}
public static void main(String args[]) {
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new Logindetails().setVisible(true);
}
});
}
// Variables declaration - do not modify
private javax.swing.JLabel Passwordvar;
private javax.swing.JLabel Usernamevar;
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JPanel jPanel1;
// End of variables declaration
}
—-----------------------------------------------------------------------------------------------
Login1.java
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JButton;
import java.awt.*;
import java.net.*;
import java.io.*;
import javax.swing.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Base64;
class Logindetail implements Serializable{
private String Username;
private String Password;
public Logindetail(String Username, String Password) {
this.Username = Username;
this.Password = Password;}
public String getUsername() {
return Username;
}
public void setUsername(String Username) {
this.Username = Username;
}
public String getPassword() {
return Password;
}
public void setPassword(String Password) {
this.Password = Password;
}
}
public class Login1 extends JFrame implements ActionListener {
JPanel contentPane;
JTextField textField;
JPasswordField passwordField;
JPanel panel = new JPanel();
JLabel lblNewLabel = new JLabel("Username:");
JLabel lblNewLabel_1 = new JLabel("Enter Login Details");
JLabel lblNewLabel_2 = new JLabel("Password:");
JButton btnNewButton = new JButton("Submit");
JButton btnNewButton_1 = new JButton("Clear");
JLabel lblNewLabel_3 = new JLabel("For Signing up CLICK BUTTON");
JButton btnNewButton_2 = new JButton("Sign up");
JLabel lblNewLabel_4 = new JLabel("HOSPITAL MANAGEMENT SYSTEM");
/**
* Launch the application.
*/
public static void main(String[] args) {
EventQueue.invokeLater(new Runnable() {
public void run() {
try {
Login1 frame = new Login1();
frame.setVisible(true);
} catch (Exception e) {
e.printStackTrace();
}
}
});
}
/**
* Create the frame.
*/
public Login1() {
contentPane = new JPanel();
setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
setBounds(100, 100, 853, 607);
contentPane.setBackground(new Color(0, 0, 64));
contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
setContentPane(contentPane);
contentPane.setLayout(null);
panel.setBounds(90, 81, 676, 355);
panel.setBackground(new Color(255, 128, 0));
contentPane.add(panel);
panel.setLayout(null);
lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 20));
lblNewLabel.setBounds(76, 81, 118, 36);
panel.add(lblNewLabel);
lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 28));
lblNewLabel_1.setBackground(new Color(0, 128, 0));
lblNewLabel_1.setBounds(217, 22, 243, 47);
panel.add(lblNewLabel_1);
lblNewLabel_2.setFont(new Font("Tahoma", Font.PLAIN, 20));
lblNewLabel_2.setBounds(76, 139, 118, 36);
panel.add(lblNewLabel_2);
textField = new JTextField();
textField.setBounds(227, 85, 181, 36);
panel.add(textField);
textField.setColumns(10);
passwordField = new JPasswordField();
passwordField.setBounds(227, 139, 181, 36);
panel.add(passwordField);
btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 14));
btnNewButton.setBounds(107, 206, 113, 36);
panel.add(btnNewButton);
btnNewButton.addActionListener(this);
btnNewButton_1.setBackground(new Color(240, 240, 240));
btnNewButton_1.setFont(new Font("Tahoma", Font.PLAIN, 15));
btnNewButton_1.setBounds(271, 206, 113, 36);
panel.add(btnNewButton_1);
btnNewButton_1.addActionListener(this);
lblNewLabel_3.setFont(new Font("Tahoma", Font.PLAIN, 15));
lblNewLabel_3.setBounds(308, 295, 213, 26);
panel.add(lblNewLabel_3);
btnNewButton_2.setBounds(531, 299, 89, 23);
panel.add(btnNewButton_2);
btnNewButton_2.addActionListener(this);
lblNewLabel_4.setForeground(new Color(255, 255, 255));
lblNewLabel_4.setFont(new Font("Tahoma", Font.PLAIN, 36));
lblNewLabel_4.setBackground(new Color(255, 255, 255));
lblNewLabel_4.setBounds(153, 11, 559, 59);
contentPane.add(lblNewLabel_4);
}
@Override
public void actionPerformed(ActionEvent e) {
String phoneno1=textField.getText();
String xphoneno=null;
String xname=null;
String xage=null;
String xgender=null;
String xproblem=null;
String xdoctor=null;
String passwordstring =passwordField.getText();
System.out.println(passwordstring);
String result="no";
if (e.getSource().equals(btnNewButton)) {
//try{
// String result= processInformation();
//}// catch (UnknownHostException e1) {
// e1.printStackTrace();
// } catch (IOException e1) {
// e1.printStackTrace();
try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection(
"jdbc:oracle:thin:@localhost:1521:xe","system","12345678");
//here sonoo is database name, root is username and password
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();
Statement stmt2=con.createStatement();
ResultSet rs=stmt.executeQuery("select * from patient where
phoneno='"+phoneno1+"'");
ResultSet rp=stmt1.executeQuery("select * from patientproblem where
phoneno='"+phoneno1+"'");
ResultSet rt=stmt2.executeQuery("select * from login where
phoneno='"+phoneno1+"'");
while(rt.next())
{
String password=rt.getString(2);
if( stringCompare(password, passwordstring)==0)
result="yes";
}
if(result=="yes")
{
while(rs.next()) {
//System.out.println(rs.getString(1)+" "+rs.getString(2)+" "+rs.getString(3)+"
"+rs.getString(4));
//con.close();
xphoneno=rs.getString(1);
xname=rs.getString(2);
xage=rs.getString(3);
xgender=rs.getString(4);
}
while(rp.next())
{
xproblem=rp.getString(2);
xdoctor=rp.getString(3);
}
new
DisplayDocter(xname,xage,xgender,xproblem,xphoneno,xdoctor).setVisible(true);
this.setVisible(false);
}
else
{
JOptionPane.showMessageDialog(this,"Enter correct details;");
}
}catch(Exception e1){ System.out.println(e1);}
}
if (e.getSource().equals(btnNewButton_2)) {
System.out.println("hello");
new Patientdetails().setVisible(true);
this.setVisible(false);
}
}
public static int stringCompare(String str1, String str2)
{
int l1 = str1.length();
int l2 = str2.length();
int lmin = Math.min(l1, l2);
for (int i = 0; i < lmin; i++) {
int str1_ch = (int)str1.charAt(i);
int str2_ch = (int)str2.charAt(i);
if (str1_ch != str2_ch) {
return str1_ch - str2_ch;
}
}
// Edge case for strings like
// String 1="Geeks" and String 2="Geeksforgeeks"
if (l1 != l2) {
return l1 - l2;
}
// If none of the above conditions is true,
// it implies both the strings are equal
else {
return 0;
}
}
public String processInformation() throws UnknownHostException, IOException {
String result="null";
try{
Socket s = new Socket("localhost", 5005);
System.out.println("client started");
ObjectOutputStream p = new ObjectOutputStream(s.getOutputStream());
String Username =textField.getText();
Base64.Encoder encoder = Base64.getEncoder();
String Passwordstring =passwordField.getText();
String Password = encoder.encodeToString(Passwordstring.getBytes());
p.writeObject(new Logindetail(Username, Passwordstring));
ObjectInputStream b = new ObjectInputStream(s.getInputStream());
Logindetail received = (Logindetail) b.readObject();
BufferedReader response = new BufferedReader(new
InputStreamReader(s.getInputStream()));
result=response.readLine();
}
catch(Exception e)
{
System.out.print(e);
}
// p.flush();
// p.close();
//s.close();
return result;
}
}
—-----------------------------------------------------------------------------------------------------------
Server.java
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.*;
import java.sql.ResultSet;
class JDBCExample {
/*static final String DB_URL = "jdbc:oracle:thin:@localhost:1521:xe";
static final String USER = "system";
static final String PASS = "aq82thna";
static int id=0;*/
public void Patients(String Phoneno, String name,String age, String gender,String
problem,String Doctor,String password,String pharmacy)
{
try{
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection(
"jdbc:oracle:thin:@localhost:1521:xe","system","12345678");
Statement stmt=con.createStatement();
System.out.println("Inserting records into the table...");
String sql ="INSERT INTO patient VALUES
('"+Phoneno+"','"+name+"','"+age+"','"+gender+"')";
String sql1="INSERT INTO patientproblem
VALUES('"+Phoneno+"','"+problem+"','"+Doctor+"','123456')";//df.format(calendar.get
Time())
String sql2="INSERT INTO login VALUES('"+Phoneno+"','"+password+"')";
String sql3="INSERT INTO pharmacy
VALUES('"+Phoneno+"','"+pharmacy+"')";
stmt.executeUpdate(sql);
stmt.executeUpdate(sql1);
stmt.executeUpdate(sql2);
stmt.executeUpdate(sql3);
}
catch(Exception e){ System.out.println(e);}
}
}
class Logindetail implements Serializable{
private String Username;
private String Password;
public Logindetail(String Username, String Password) {
this.Username = Username;
this.Password = Password;}
public String getUsername() {
return Username;
}
public void setUsername(String Username) {
this.Username = Username;
}
public String getPassword() {
return Password;
}
public void setPassword(String Password) {
this.Password = Password;
}
}
class patientinfo implements Serializable{
private String name;
private String age;
private String phoneno;
private String Gender;
private String Problem;
private String password;
private String doctor;
private String pharmacy;
public patientinfo(String name, String age, String gender,String problem,String
password,String phoneno,String doctor,String pharmacy) {
this.name = name;
this.age = age;
this.Gender = gender;
this.Problem=problem;
this.password=password;
this.phoneno=phoneno;
this.doctor=doctor;
this.pharmacy=pharmacy;
}
public String getName() {
return name;
}
public void setName(String name) {
this.name = name;
}
public String getAge() {
return age;
}
public void setAge(String age) {
this.age = age;
}
public String getGender() {
return Gender;
}
public void setGender(String gender) {
this.Gender = gender;
}
public String getPhoneno() {
return phoneno;
}
public void setPhoneno(String phoneno) {
this.phoneno = phoneno;
}
public String getProblem() {
return Problem;
}
public void setProblem(String problem) {
this.Problem = problem;
}
public String getPassword() {
return password;
}
public void setPassword(String password) {
this.password = password;
}
public String getDoctor() {
return doctor;
}
public void setDoctor(String doctor) {
this.doctor = doctor;
}
public String getPharmacy() {
return pharmacy;
}
public void setPharmacy(String pharmacy) {
this.pharmacy = pharmacy;
}
}
public class Server {
public static void main(String[] argv) throws Exception {
ServerSocket s = new ServerSocket(5000);
JDBCExample ex=new JDBCExample();
System.out.println("Server started");
boolean i=true;
//while (i) {
Socket t = s.accept();// wait for client to connect
System.out.println("server connected");
ObjectInputStream b = new ObjectInputStream(t.getInputStream());
patientinfo received = (patientinfo) b.readObject();
String problem=received.getProblem();
ex.Patients(received.getPhoneno(),received.getName(),received.getAge(),received.g
etGender(),problem,received.getDoctor(),received.getPassword(),received.getPharm
acy());
}
}
—--------------------------------------------------------------------------------------------------------
Patientdetails.java
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JButton;
import java.awt.*;
import java.net.*;
import java.io.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.Base64;
class patientinfo implements Serializable{
private String name;
private String age;
private String phoneno;
private String Gender;
private String Problem;
private String password;
private String doctor;
private String pharmacy;
public patientinfo(String name, String age, String gender,String problem,String
password,String phoneno,String doctor,String pharmacy) {
this.name = name;
this.age = age;
this.Gender = gender;
this.Problem=problem;
this.password=password;
this.phoneno=phoneno;
this.doctor=doctor;
this.pharmacy=pharmacy;
}
public String getName() {
return name;
}
public void setName(String name) {
this.name = name;
}
public String getAge() {
return age;
}
public void setAge(String age) {
this.age = age;
}
public String getGender() {
return Gender;
}
public void setGender(String gender) {
this.Gender = gender;
}
public String getPhoneno() {
return phoneno;
}
public void setPhoneno(String phoneno) {
this.phoneno = phoneno;
}
public String getProblem() {
return Problem;
}
public void setProblem(String problem) {
this.Problem = problem;
}
public String getPassword() {
return password;
}
public void setPassword(String password) {
this.password = password;
}
public String getDoctor() {
return doctor;
}
public void setDoctor(String doctor) {
this.doctor = doctor;
}
public String getPharmacy() {
return pharmacy;
}
public void setPharmacy(String pharmacy) {
this.pharmacy = pharmacy;
}
}
public class Patientdetails extends javax.swing.JFrame {
public Patientdetails() {
initComponents();
}
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {
femalevar = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
namevar = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
agevar = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
problemvar = new javax.swing.JComboBox<>();
jLabel5 = new javax.swing.JLabel();
malevar = new javax.swing.JRadioButton();
femalevarr = new javax.swing.JRadioButton();
jLabel6 = new javax.swing.JLabel();
passwordvar = new javax.swing.JTextField();
jButton1 = new javax.swing.JButton();
phonenovar = new javax.swing.JTextField();
Pagetitle = new javax.swing.JLabel();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setBackground(new java.awt.Color(255, 51, 0));
femalevar.setBackground(new java.awt.Color(51, 0, 102));
femalevar.setForeground(new java.awt.Color(242, 242, 242));
jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel1.setForeground(new java.awt.Color(242, 242, 242));
jLabel1.setText("Name:");
namevar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
namevar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
namevarActionPerformed(evt);
}
});
jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel2.setForeground(new java.awt.Color(242, 242, 242));
jLabel2.setText("Age:");
agevar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
agevar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
agevarActionPerformed(evt);
}
});
jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel3.setForeground(new java.awt.Color(242, 242, 242));
jLabel3.setText("Phone No.:");
jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel4.setForeground(new java.awt.Color(242, 242, 242));
jLabel4.setText("Problem:");
problemvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
problemvar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
{ "fever", "cold", "cough", "corona" }));
problemvar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
problemvarActionPerformed(evt);
}
});
jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel5.setForeground(new java.awt.Color(242, 242, 242));
jLabel5.setText("Gender:");
malevar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
malevar.setText("Male");
femalevarr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
femalevarr.setText("Female");
jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
jLabel6.setForeground(new java.awt.Color(242, 242, 242));
jLabel6.setText("Enter Password:");
passwordvar.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
passwordvarActionPerformed(evt);
}
});
jButton1.setBackground(new java.awt.Color(255, 102, 0));
jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
jButton1.setText("Submit");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});
javax.swing.GroupLayout femalevarLayout = new
javax.swing.GroupLayout(femalevar);
femalevar.setLayout(femalevarLayout);
femalevarLayout.setHorizontalGroup(
femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING
)
.addGroup(femalevarLayout.createSequentialGroup()
.addGap(27, 27, 27)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.TRAILING)
.addComponent(jButton1,
javax.swing.GroupLayout.PREFERRED_SIZE, 156,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.LEADING, false)
.addGroup(femalevarLayout.createSequentialGroup()
.addComponent(jLabel6)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(passwordvar))
.addGroup(femalevarLayout.createSequentialGroup()
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.LEADING, false)
.addComponent(jLabel5,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel4,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel3,
javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
.addComponent(jLabel2,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel1,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGap(26, 26, 26)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.LEADING, false)
.addComponent(namevar)
.addComponent(agevar)
.addComponent(problemvar, 0,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(femalevarLayout.createSequentialGroup()
.addComponent(malevar)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30,
Short.MAX_VALUE)
.addComponent(femalevarr))
.addComponent(phonenovar)))))
.addContainerGap(173, Short.MAX_VALUE))
);
femalevarLayout.setVerticalGroup(
femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING
)
.addGroup(femalevarLayout.createSequentialGroup()
.addGap(22, 22, 22)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.LEADING, false)
.addGroup(femalevarLayout.createSequentialGroup()
.addGap(2, 2, 2)
.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
31, Short.MAX_VALUE))
.addComponent(namevar,
javax.swing.GroupLayout.PREFERRED_SIZE, 29,
javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.LEADING, false)
.addComponent(agevar, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
Short.MAX_VALUE)
.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGap(18, 18, 18)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.TRAILING)
.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
31, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(femalevarLayout.createSequentialGroup()
.addComponent(phonenovar,
javax.swing.GroupLayout.PREFERRED_SIZE, 30,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(2, 2, 2)))
.addGap(18, 18, 18)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.TRAILING)
.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
31, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(femalevarLayout.createSequentialGroup()
.addComponent(problemvar,
javax.swing.GroupLayout.PREFERRED_SIZE, 31,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(2, 2, 2)))
.addGap(18, 18, 18)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.BASELINE)
.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
31, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(malevar)
.addComponent(femalevarr))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(femalevarLayout.createParallelGroup(javax.swing.GroupLayout.Alignme
nt.LEADING, false)
.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
Short.MAX_VALUE)
.addComponent(passwordvar))
.addGap(18, 18, 18)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
35, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(20, Short.MAX_VALUE))
);
Pagetitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
Pagetitle.setText("PLEASE ENTER YOU DETAILS");
javax.swing.GroupLayout layout = new
javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(29, 29, 29)
.addComponent(femalevar, javax.swing.GroupLayout.PREFERRED_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(52, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE)
.addComponent(Pagetitle, javax.swing.GroupLayout.PREFERRED_SIZE,
257, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(133, 133, 133))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(13, 13, 13)
.addComponent(Pagetitle, javax.swing.GroupLayout.PREFERRED_SIZE,
28, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(femalevar, javax.swing.GroupLayout.PREFERRED_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(33, Short.MAX_VALUE))
);
pack();
}// </editor-fold>
private void namevarActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void problemvarActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void passwordvarActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
String name=namevar.getText();
String age=agevar.getText();
String gender="null";
if(malevar.isSelected()){
gender="male";}
if(femalevarr.isSelected()){
gender="female";}
String phoneno=phonenovar.getText();
String problem="null";
String doctor=null;
String pharmacy=null;
if(problemvar.getSelectedItem().equals("fever"))
{
problem="fever";
doctor="Ramesh";
pharmacy="Paracetamol(quatity-10 three times a day after food)
,Ibuprofen(quatity-10 two times a day after food) ";
}
if(problemvar.getSelectedItem().equals("cold"))
{
problem="cold";
doctor="Ravi";
pharmacy="Piriton(quatity-10 three times a day after food)
,Cetirizine(quatity-10 two times a day after food)";
}
if(problemvar.getSelectedItem().equals("cough"))
{
problem="cough";
doctor="pranav";
pharmacy="cofsils(take 5ml of tonic 2 times a day after food),Theraflu Cough
Relief(quatity-4 after once after dinner)";
}
if(problemvar.getSelectedItem().equals("corona"))
{
problem="corona";
doctor="seetha";
pharmacy="Paxlovid(quatity-10 two times a day after food)";
}
String password=passwordvar.getText();
try{
Socket s = new Socket("localhost", 5000);
ObjectOutputStream t = new ObjectOutputStream(s.getOutputStream());
t.writeObject(new
patientinfo(name,age,gender,problem,password,phoneno,doctor,pharmacy));}
catch (UnknownHostException e1) {
e1.printStackTrace();
} catch (IOException e1) {
e1.printStackTrace();
}
//Logindetails u=new Logindetails();
// String phone=Integer.toString(phoneno);
new
Logindetails(name,age,gender,problem,phoneno,password,doctor).setVisible(true);
//new Logindetails(phone,password).setVisible(true);
}
private void agevarActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}
public static void main(String args[]) {
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new Patientdetails().setVisible(true);
}
});
}
// Variables declaration - do not modify
private javax.swing.JLabel Pagetitle;
private javax.swing.JTextField agevar;
private javax.swing.JPanel femalevar;
private javax.swing.JRadioButton femalevarr;
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JRadioButton malevar;
private javax.swing.JTextField namevar;
private javax.swing.JTextField passwordvar;
private javax.swing.JTextField phonenovar;
private javax.swing.JComboBox<String> problemvar;
// End of variables declaration
}
—-------------------------------------------------------------------------------------------------------------
pharmaServer.java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
class pharma{
String phone;
public pharma(String phoneno)
{
this.phone=phoneno;
}
public void setphone(String phoneno)
{
this.phone=phoneno;
}
public String getphoneno()
{
return phone;
}
}
public class pharmaServer {
public String server(String phoneno1){
String result=null;
String xphoneno=null;
String xname=null;
String xage=null;
String xgender=null;
String xproblem=null;
String xdoctor=null;
String xpharmacy=null;
String s1=null;
String s2=null;
String s3=null;
String s4=null;
String s5=null;
String s6=null;
String s7=null;
String s8=null;
// String s9=null;
//String s10=null;
//String s11=null;
try {
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection(
"jdbc:oracle:thin:@localhost:1521:xe","system","12345678");
//here sonoo is database name, root is username and password
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();
Statement stmt2=con.createStatement();
ResultSet rs=stmt.executeQuery("select * from patient where
phoneno='"+phoneno1+"'");
ResultSet rp=stmt1.executeQuery("select * from patientproblem where
phoneno='"+phoneno1+"'");
ResultSet rt=stmt2.executeQuery("select * from pharmacy where
phoneno='"+phoneno1+"'");
while(rs.next()) {
//System.out.println(rs.getString(1)+" "+rs.getString(2)+" "+rs.getString(3)+"
"+rs.getString(4));
//con.close();
xphoneno=rs.getString(1);
xname=rs.getString(2);
xage=rs.getString(3);
xgender=rs.getString(4);
}
while(rp.next())
{
xproblem=rp.getString(2);
xdoctor=rp.getString(3);
}
while(rt.next())
{
xpharmacy=rt.getString(2);
}
s1=" HOSPITAL MANAGEMENT SYSTEM ";
s2=String.join(" ","Name:",xname);
s3=String.join(" ","Age:",xage);
s4=String.join(" ","Gender:",xgender);
s5=String.join(" ","Problem:",xproblem);
s6=String.join(" ","Phone number:",xphoneno);
s7=String.join(" ","Doctor name:",xdoctor);
s8=String.join(" ","PHARMACY DETAILS:",xpharmacy);
result=String.join("\n",s1,s2,s3,s4,s5,s6,s7,s8);
}catch(Exception e1){ System.out.println(e1);}
return result;
}
public static int stringCompare(String str1, String str2)
{
int l1 = str1.length();
int l2 = str2.length();
int lmin = Math.min(l1, l2);
for (int i = 0; i < lmin; i++) {
int str1_ch = (int)str1.charAt(i);
int str2_ch = (int)str2.charAt(i);
if (str1_ch != str2_ch) {
return str1_ch - str2_ch;
}
}
// Edge case for strings like
// String 1="Geeks" and String 2="Geeksforgeeks"
if (l1 != l2) {
return l1 - l2;
}
// If none of the above conditions is true,
// it implies both the strings are equal
else {
return 0;
}
}
public static void main(String args[])
{
pharmaServer ps=new pharmaServer();
System.out.println("server started");
System.out.println(ps.server("9123456780"));
}
}
—-------------------------------------------------------------------------------------------------------
Emailsender.java
/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to
change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this
template
*/
/**
*
* @author Nishanth
*/
import com.email.durgesh.*;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
public class Emailsender {
public static void sendmail(String recepient) throws Exception
{
System.out.println("sending mail");
Properties properties=new Properties();
properties.put("mail.smtp.auth","true");
properties.put("mail.smtp.starttls.enable","true");
properties.put("mail.smtp.starttls.required","true");
properties.put("mail.smtp.host","smtp.gmail.com");
properties.put("mail.smtp.port","587");
properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
String myAccountemail="124003074@sastra.ac.in";
String password="jyothi7893";
Session session=Session.getInstance(properties,new Authenticator(){
@Override
protected PasswordAuthentication getPasswordAuthentication(){
return new PasswordAuthentication(myAccountemail,password);
}
});
Message message=prepareMessage(session,myAccountemail,recepient);
try{
Transport.send(message);
System.out.println("meaasge send successfully");
}
catch(Exception e)
{
System.out.println(e);
}
}
private static Message prepareMessage(Session session,String
myAccountemail,String recepient)
{
Message message=new MimeMessage(session);
try
{
pharmaServer ps=new pharmaServer();
String n=ps.server("9123456780");
message.setFrom(new InternetAddress(myAccountemail));
message.setRecipient(Message.RecipientType.TO,new
InternetAddress(recepient));
message.setSubject("MY mail");
message.setText(n);
// message.setText("hey there,\n look the mail");
return message;
}catch(Exception e)
{
System.out.println(e);
}return null;
}
/* public static void main(String Args[])
{
try{
Email email=new Email("124003074@sastra.ac.in","jyothi7893");
email.setFrom("124003074@sastra.ac.in","uff");
email.setSubject("this is for testing");
email.setContent("<h1>this is con tent</h1>","text/html");
email.addRecipient("nishanthdamarancha0106@gmail.com");
email.send();
}
catch(Exception e)
{
e.printStackTrace();
}
}*/
}
—-------------------------------------------------------------------------------------------------------------
Emailsender.java
/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to
change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this
template
*/
/**
*
* @author Nishanth
*/
import com.email.durgesh.*;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
public class Emailsender {
public static void sendmail(String recepient) throws Exception
{
System.out.println("sending mail");
Properties properties=new Properties();
properties.put("mail.smtp.auth","true");
properties.put("mail.smtp.starttls.enable","true");
properties.put("mail.smtp.starttls.required","true");
properties.put("mail.smtp.host","smtp.gmail.com");
properties.put("mail.smtp.port","587");
properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
String myAccountemail="124003074@sastra.ac.in";
String password="jyothi7893";
Session session=Session.getInstance(properties,new Authenticator(){
@Override
protected PasswordAuthentication getPasswordAuthentication(){
return new PasswordAuthentication(myAccountemail,password);
}
});
Message message=prepareMessage(session,myAccountemail,recepient);
try{
Transport.send(message);
System.out.println("meaasge send successfully");
}
catch(Exception e)
{
System.out.println(e);
}
}
private static Message prepareMessage(Session session,String
myAccountemail,String recepient)
{
Message message=new MimeMessage(session);
try
{
pharmaServer ps=new pharmaServer();
String n=ps.server("9123456780");
message.setFrom(new InternetAddress(myAccountemail));
message.setRecipient(Message.RecipientType.TO,new
InternetAddress(recepient));
message.setSubject("MY mail");
message.setText(n);
// message.setText("hey there,\n look the mail");
return message;
}catch(Exception e)
{
System.out.println(e);
}return null;
}
/* public static void main(String Args[])
{
try{
Email email=new Email("124003074@sastra.ac.in","jyothi7893");
email.setFrom("124003074@sastra.ac.in","uff");
email.setSubject("this is for testing");
email.setContent("<h1>this is con tent</h1>","text/html");
email.addRecipient("nishanthdamarancha0106@gmail.com");
email.send();
}
catch(Exception e)
{
e.printStackTrace();
}
}*/
}
—-----------------------------------------------------------------------------------------------
JavaMail.java
/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to
change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this
template
*/
/**
*
* @author Nishanth
*/
public class JavaMail {
public static void main(String Args[]) throws Exception
{
Emailsender.sendmail("kolluchethanreddy@gmail.com");
}
}
================================================================
